### ISSUE TITLE
Soundmanager2

### ISSUE THREAD

**Issue by r14c** [lancejpollard/cached-commons#1]
This JS library exposes an amazing sound API via flash (with experimental HTML5 support)

http://github.com/scottschiller/SoundManager2

**Comment by lancejpollard** [comment]
Thanks, added!  Since this references swfs, I have a swfs folder with the swfs that you can also use in case you were wondering.

For swfs/css, check these directories:
- [http://github.com/viatropos/cached-commons/tree/master/stylesheets](http://github.com/viatropos/cached-commons/tree/master/stylesheets)
- [http://github.com/viatropos/cached-commons/tree/master/swfs](http://github.com/viatropos/cached-commons/tree/master/swfs)
- [http://github.com/viatropos/cached-commons/tree/master/images](http://github.com/viatropos/cached-commons/tree/master/images)

Those can be linked to similarly:
- http://cachedcommons.org/stylesheets/...
- http://cachedcommons.org/swfs/...
- http://cachedcommons.org/images/...

Best,
Lance

**Comment by r14c** [comment]
Sweet!
